import { Home } from "@/home";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Homie() {
  return (
    <Home/>
  );
}
